name: Build Android and create release.

on:
  push:
    tags:
      - "v*" # Push events matching v*, i.e. v1.0, v20.15.10

defaults:
  run:
    working-directory: mobile

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set release name using tag
        id: version
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Install dependencies
        run: yarn install

      - name: Build Android release
        run: yarn run android:assemble:development

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.tag }}
          release_name: ${{ steps.version.outputs.tag }}
          draft: false
          prerelease: false

      - name: Upload release apk
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: mobile/android/app/build/outputs/apk/debug/amamentacoach-${{ steps.version.outputs.tag }}-debug.apk
          asset_name: amamentacoach-${{ steps.version.outputs.tag }}.apk
          asset_content_type: application/zip
